// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaQltwJRKIrmJVvy7mqZDFm1rEdks7-hc',
    appId: '1:869507926912:web:1e18fa1d7aa8c870d70f65',
    messagingSenderId: '869507926912',
    projectId: 'safezone-a02e7',
    authDomain: 'safezone-a02e7.firebaseapp.com',
    storageBucket: 'safezone-a02e7.firebasestorage.app',
    measurementId: 'G-W50W5V8N0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCCZkfBOh3YKDKOQrO5N-OaPZBYFgNCfw',
    appId: '1:869507926912:android:f52406f0a3cb1b7bd70f65',
    messagingSenderId: '869507926912',
    projectId: 'safezone-a02e7',
    storageBucket: 'safezone-a02e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcYtk0QywUV1N1rXSxHnHRb_dIS41mYrY',
    appId: '1:869507926912:ios:3fdd87b7ed555fefd70f65',
    messagingSenderId: '869507926912',
    projectId: 'safezone-a02e7',
    storageBucket: 'safezone-a02e7.firebasestorage.app',
    iosBundleId: 'com.safezone.safezone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcYtk0QywUV1N1rXSxHnHRb_dIS41mYrY',
    appId: '1:869507926912:ios:3fdd87b7ed555fefd70f65',
    messagingSenderId: '869507926912',
    projectId: 'safezone-a02e7',
    storageBucket: 'safezone-a02e7.firebasestorage.app',
    iosBundleId: 'com.safezone.safezone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaQltwJRKIrmJVvy7mqZDFm1rEdks7-hc',
    appId: '1:869507926912:web:be365fac85328f7ed70f65',
    messagingSenderId: '869507926912',
    projectId: 'safezone-a02e7',
    authDomain: 'safezone-a02e7.firebaseapp.com',
    storageBucket: 'safezone-a02e7.firebasestorage.app',
    measurementId: 'G-ZDL27XP681',
  );
}
